apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: enxtur-website-tls
spec:
  secretName: enxtur-website
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: enxtur.website
  dnsNames:
    - enxtur.website
    - www.enxtur.website
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - enxtur.website
          - www.enxtur.website
